// <auto-generated />
using System;
using EFCoreRelations.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreRelations.Migrations
{
    [DbContext(typeof(AirLineDbContext))]
    [Migration("20251125160622_IntialMigration")]
    partial class IntialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreRelations.Models.AirCraft", b =>
                {
                    b.Property<int>("AirCraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirCraftId"));

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirCraftId");

                    b.HasIndex("AirLineId");

                    b.ToTable("AirCrafts");
                });

            modelBuilder.Entity("EFCoreRelations.Models.AirLine", b =>
                {
                    b.Property<int>("AirLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirLineId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cont_Person")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirLineId");

                    b.ToTable("AirLines");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Crew", b =>
                {
                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<string>("Assis_Pilot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maj_Pilot")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrewId");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<int>("BD_Day")
                        .HasColumnType("int");

                    b.Property<int>("BD_Month")
                        .HasColumnType("int");

                    b.Property<int>("BD_Year")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpId");

                    b.HasIndex("AirLineId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("EFCoreRelations.Models.RouteAircraft", b =>
                {
                    b.Property<int>("AirCraftId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("NumOfPassengers")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AirCraftId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteAircraft");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Transaction", b =>
                {
                    b.Property<int>("TranactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranactionId"));

                    b.Property<int>("AirLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TranactionId");

                    b.HasIndex("AirLineId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("EFCoreRelations.Models.AirCraft", b =>
                {
                    b.HasOne("EFCoreRelations.Models.AirLine", "AirLine")
                        .WithMany("airCrafts")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirLine");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Crew", b =>
                {
                    b.HasOne("EFCoreRelations.Models.AirCraft", "CAirCraft")
                        .WithOne("ACrew")
                        .HasForeignKey("EFCoreRelations.Models.Crew", "CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CAirCraft");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Employee", b =>
                {
                    b.HasOne("EFCoreRelations.Models.AirLine", "EAirline")
                        .WithMany("employees")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EAirline");
                });

            modelBuilder.Entity("EFCoreRelations.Models.RouteAircraft", b =>
                {
                    b.HasOne("EFCoreRelations.Models.AirCraft", "NAirCraft")
                        .WithMany("ArouteAircraft")
                        .HasForeignKey("AirCraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreRelations.Models.Route", "NRoute")
                        .WithMany("RrouteAircraft")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NAirCraft");

                    b.Navigation("NRoute");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Transaction", b =>
                {
                    b.HasOne("EFCoreRelations.Models.AirLine", "TAirLine")
                        .WithMany("transactions")
                        .HasForeignKey("AirLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TAirLine");
                });

            modelBuilder.Entity("EFCoreRelations.Models.AirCraft", b =>
                {
                    b.Navigation("ACrew")
                        .IsRequired();

                    b.Navigation("ArouteAircraft");
                });

            modelBuilder.Entity("EFCoreRelations.Models.AirLine", b =>
                {
                    b.Navigation("airCrafts");

                    b.Navigation("employees");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("EFCoreRelations.Models.Route", b =>
                {
                    b.Navigation("RrouteAircraft");
                });
#pragma warning restore 612, 618
        }
    }
}
